ppm: null # should be in Study record
smoothing_factor: 3 # should be in Study record
useMatchedCut: false
arena_size: [50, 50] # should be in arena record
speed_lowerbound: 3 # should be in Study record
speed_upperbound: 100 # should be in Study record
end_cell: null
start_cell: null
num_bins: 16
saveData: true
saveMethod: 'one_per_parent'

tasks:
  disk_arena: false
  spike_width: true
  spike_analysis: true
  binary_map: true
  autocorrelation_map: true
  sparsity: true
  selectivity: true
  information: true
  coherence: true
  speed_score: true
  hd_score: true
  tuning_curve: true
  grid_score: true
  border_score: true
  field_sizes: true

plotTasks:
  binary_map: true
  occupancy_map: true
  Waveforms_Across_Channels: true
  Spikes_Over_Position_Map: true
  Tuning_Curve_Plots: true
  Firing_Rate_vs_Speed_Plots: true
  Firing_Rate_vs_Time_Plots: true
  autocorr_map: true
  binary_map_2d: true
  rate_map: true

header:
  spike_width: true
  spike_count: true
  firing_rate: true
  Avg. Spikes/Burst: true
  bursting: true
  iso_dist: true
  L_ratio: true
  ISI_min: true
  ISI_median: true
  ISI_cv: true
  ISI_std: true
  sparsity: true
  selectivity: true
  information: true
  coherence: true
  speed_score: true
  hd_score: true
  grid_score: true
  border_score: true
  field_sizes: true